name: 部署master分支代码到腾讯云函数

on:
  schedule:
    - cron: '6 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: checkoutMain
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: master

      - name: checkoutMaster
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: main
          path: main

      - name: 查看目录
        run: mv -f main/serverless.yml serverless.yml
