name: 同步大佬代码并触发部署
on:
  schedule:
    - cron: '5 0,15 * * *'
  workflow_dispatch:
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: master

      - name: sync lxk0301-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ env.PAT }}

      - name: update index.js
        run: |
          sed -i \
          -e 's#//delete#delete#' \
          -e 's#//require(#require(#' \
          -e 's#      var request#//      var request#' \
          -e 's#      request(#//      request(#' \
          -e 's#        eval(#//        eval(#' \
          -e 's#      })#//      })#' \
          index.js
#          git config --global user.email VIP2925757292@gmail.com
#          git config --global user.name ${{ github.repository_owner }}
#          git config pull.rebase false
#          git pull origin master
#          git reset --hard master
#          git add index.js
#          git commit -m 'update index.js'
#          git push -u origin master -f

      - name: Git Commit and Push Force
        uses: rahularyan/commit@1.0.0\
        with:
          github-token: ${{ env.PAT }}
          push-branch: 'master'
          force-add: 'true'
          files: index.js

      - name: 触发部署到腾讯云函数
        if: env.PAT && github.event_name == 'schedule'  #只有定时任务才触发部署
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ env.PAT }}" \
            -d '{"ref":"master"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy_tencent_scf.yml/dispatches

      - name: Notify To Telegram
        if: env.TG_USER_ID && env.TG_BOT_TOKEN
        run: |
          curl \
            -s -o /dev/null \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{"text": "${{github.workflow}} 运行成功！","chat_id": "${{ env.TG_USER_ID }}"}' \
            https://api.telegram.org/bot${{ env.TG_BOT_TOKEN }}/sendMessage
