# File: .github/workflows/repo-sync.yml
name: 同步大佬代码并触发部署
on:
  schedule:
    - cron: '5 0,15 * * *'
  workflow_dispatch:
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: sync lxk0301-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
            
      - name: 触发部署到腾讯云函数
        if: github.event.sender.type != User
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -d '{"ref":"master"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy_tencent_scf.yml/dispatches

      - name: Notify To Telegram
        run: |
          curl \
            -s -o /dev/null \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{"text": "${{github.workflow}} 运行成功！","chat_id": "${{ secrets.TG_USER_ID }}"}' \
            https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage
